cloudquery/cq-provider-sdk

provider/providertest/resource.go

This PR adds a small test flag (opt-in) that allows tests to skip the empty jsonb validation step.

Add empty jsonb test skip flag

---

provider/providertest/resource.go

Check a few ignored errors.
Use require instead of assert to fail early.

Add more checks for errors.

---

provider/schema/database.go
provider/schema/database_test.go
provider/schema/execution.go
provider/schema/execution_test.go

If copy-from fails try to normal "slower" insert, if conflicts arise on insert still fail. Future version can support single insert after conflict, on conflict print warning and continue.

insert on failed copy-from

---

go.mod
go.sum
provider/provider.go
provider/schema/database.go
provider/schema/execution.go
provider/schema/resource.go

- Print SQL in case of syntax error
- Only print resource primary keys in case of insert failure instead of full resource.

update sdk logging for syntax insert error

---

provider/schema/execution.go

Fixes #114
It's not easy to get the value in general but the column name is possible.

Add column name to resolver errors

---

provider/provider.go
provider/schema/execution.go

fixes: https://github.com/cloudquery/cloudquery/issues/285

Add Warning About File Descriptor Usage

---

provider/testing/integration.go

Using the default logging because that is what we are using in the rest of this package
Implements: https://github.com/cloudquery/cloudquery-issues/issues/167

Add TF logging

---

CHANGELOG.md
provider/testing/resource.go

Passing the `*testing.T` to a fn to do further tests (which called `t.Parallel()`) was making the tests run parallel from then on, which is bad. Also sub-sub-relations weren't getting tested.

Fix parallel tests for identifiers

---

provider/migrations.go
provider/provider.go

I made a function visible to be used by cloudquery core for migrations

make read migration files visible outside package

---

database/dsn/dsn.go
database/postgres/connection.go

pgconn does a good job of redacting the password, but it wraps the net/url's parse error, which includes the original URI
dburl returns url.Parse errors as-is

fix: Redact DSN parse errors

---

migration/table.go
provider/schema/column.go

This will stop the warning messages when running properly
It will start adding cq_fetch_date if running on an improperly initialised (not TSDB, but in `tsdb://` mode) DB though

fix: Migrator should consider dialect columns

---

provider/provider.go
serve/serve.go

info level maybe too low, make it warn? not sure.

fix: Allow reconfiguring provider in unmanaged mode

---

provider/provider.go
provider/schema/execution.go

```
✓ cq-provider-aws@latest fetch complete    2s   Finished Resources: 1/1
Fetch Diagnostics for provider aws:
Resource: sagemaker.training_jobs Type: Resolving Severity: Error
Summary: failed to resolve resource: recovered from panic: runtime error: invalid memory address or nil pointer dereference
Provider fetch complete.
Provider aws fetch summary: ✓ Total Resources fetched: 1         ⚠️ Warnings: 0  ❌ Errors: 1
```

fix: Sub-resource partial fetch error handling

---

database/dsn/dsn.go
database/dsn/dsn_test.go

If the DSN manages to pass through a net.Addr parser and fails there, `net.AddrError` leaks connection details in the error message.

fix: More DSN redactions

---

provider/diag/diagnostics.go
provider/diag/diagnostics_test.go
provider/diag/squash.go

This way you could squash a diag multiple times, also warning/error counts are corrected

fix: Better counting of squashed diagnostics

---

provider/testing/resource.go

Fixes an issue where tests failed if the local postgresql had a different schema.
For example, if I added a column to a table (but postgresql still has the old table schema),
the tests would fail (because we ran "CREATE TABLE IF NOT EXISTS" and "DELETE FROM", but at no point did we actually add the new column).
It's better to drop and recreate them entirely, I believe.

test: Fix test failures when local postgres instance has a different table schema

---

migration/table.go
provider/provider.go
provider/testing/resource.go

TableCreator: No more CreateTable(), fix it in the one place it is used
Config Template: Remove `enable_partial_fetch = true` as it's always assumed true after https://github.com/cloudquery/cloudquery/pull/495

fix: Clean up tablecreator, remove enable_partial_fetch in config template

---

database/postgres/pgdatabase.go
provider/execution/execution.go

Inserting singly starts failing with bad column quotation after first operation.

fix: Single insert

---

migration/migrator/migrator.go
migration/migrator/migrator_test.go
migration/testbuilder.go

This was needed to be able to 'drop views' on timescaledb dialect executor before the migrator was run.

feat: Add migrator prehook

---

serve/reattach.go

Tests sometimes fail with "invalid json", maybe it attempts reading before the file is closed/flushed on the provider side? This might fix it.

fix: Clean up reattach file reading

---

provider/testing/resource.go

When an entire table is ignored, then we should just skip fetching: https://github.com/cloudquery/cq-provider-gcp/pull/190
This only works for parent tables though

feat: Ignore Table Completely in test

---

provider/diag/diagnostics.go

fix: Count panics as error in diags.Errors()

---

provider/testing/resource.go
provider/testing/verifiers.go

Hi! 
In [yandex-cloud provider](https://github.com/yandex-cloud/cq-provider-yandex) we want to verify more complex conditions than just non-empty columns. So I suggest to provide opportunity of writing custom verifiers for user.

feat: Testing. More ways to verify table content.

---

provider/module/module.go

`filepath` leads to `\` which is no good.

fix: Modulefiles on Windows

---

cqproto/internal/plugin.pb.go
cqproto/internal/plugin_grpc.pb.go
provider/execution/execution.go
provider/execution/execution_test.go
provider/provider.go
provider/schema/meta.go

Execution Logger starts with "table" -> table base implied args, on each client execution we add clients implied args + client id.
On relations we add another With arg called relation. Might require some more tweaking

feat: Improved execution logging

---

provider/diag/error.go

fix: Diag detail

---

provider/schema/column.go

Now sdk can automatically marshal slices of pointers to `json`

fix: Added json marshaling for []*struct -> json
